apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployments
  labels:
    env: dev
    appType: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      appType: backend
  template:
    metadata:
      labels:
        env: dev
        appType: backend
    spec:
      containers:
        - name: nodejs-pod
          image: devildeveloper/nodejs-docker-demo:v1.0.0
          env:
            - name: "PORT"
              value: "4040"
          ports:
            - containerPort: 4040
          resources:
            limits:
              memory: "200Mi"
              cpu: "1"
            requests:
              memory: "100Mi"
              cpu: "0.5"