apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer
  selector:
    env: dev
    appType: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4040